#ifndef __STD_LIMITS_H
#define __STD_LIMITS_H

#define CHAR_WIDTH 8
#define SHRT_WIDTH 16
#define INT_WIDTH 32
#define LONG_WIDTH 64
#define LLONG_WIDTH LONG_WIDTH
#define SCHAR_WIDTH CHAR_WIDTH
#define UCHAR_WIDTH CHAR_WIDTH
#define USHRT_WIDTH SHRT_WIDTH
#define UINT_WIDTH INT_WIDTH
#define ULONG_WIDTH LONG_WIDTH
#define ULLONG_WIDTH LONG_WIDTH
#define CHAR_BIT CHAR_WIDTH

#define CHAR_MAX   0x7F
#define UCHAR_MAX  0xFF
#define SHRT_MAX   0x7FFF
#define USHRT_MAX  0xFFFF
#define INT_MAX    0x7FFFFFFF
#define UINT_MAX   0xFFFFFFFFU
#define LONG_MAX   0x7FFFFFFFFFFFFFFFL
#define ULONG_MAX  0xFFFFFFFFFFFFFFFFUL
#define CHAR_MIN   (-1-CHAR_MAX)
#define SHRT_MIN   (-1-SHRT_MAX)
#define INT_MIN    (-1-INT_MAX)
#define LONG_MIN   (-1-LONG_MAX)
#define SCHAR_MIN  CHAR_MIN
#define SCHAR_MAX  CHAR_MAX
#define LLONG_MIN  LONG_MIN
#define LLONG_MAX  LONG_MAX
#define ULLONG_MAX ULONG_MIN

#endif
